.github/workflows/pull_request.yml, PIA VPN.xcodeproj/project.pbxproj, PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA VPN.xcscheme, fastlane/Fastfile
- Optimizations on the build and test workflow by reducing the time it takes to run the e2e tests
- Fixed some crashes that were happening during the unit and e2e tests execution
=> PIA-865: Update e2e ci pipeline workflow

PIA VPN.xcodeproj/project.pbxproj, PIA VPN/Tiles/QuickSettingsTileCollectionViewCell.swift, PIA-VPN_E2E_Tests/Core/BaseTest.swift, PIA-VPN_E2E_Tests/Helpers/ElementHelper.swift, PIA-VPN_E2E_Tests/Screens/HomeScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/QuickSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/SettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/SideMenuScreen.swift, PIA-VPN_E2E_Tests/Tests/OnboardingTests.swift, PIA-VPN_E2E_Tests/Tests/QuickSettingsTests.swift, PIA-VPN_E2E_Tests/Tests/SignInTests.swift, PIA-VPN_E2E_Tests/Tests/UpdateSettingsTests.swift
**Summary**
Added Quick Settings Tests, Enhanced existing screens and tests.
Fixes #
=> PIA-865 [iOS] Quick Settings Tests

PIA VPN-tvOS/Assets.xcassets/AccentColor.colorset/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json, PIA VPN-tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json, PIA VPN-tvOS/Assets.xcassets/Contents.json, PIA VPN-tvOS/ContentView.swift, PIA VPN-tvOS/PIA_VPN_tvOSApp.swift, PIA VPN-tvOS/Preview Content/Preview Assets.xcassets/Contents.json, PIA VPN-tvOSTests/PIA_VPN_tvOSTests.swift, PIA VPN-tvOSUITests/PIA_VPN_tvOSUITests.swift, PIA VPN-tvOSUITests/PIA_VPN_tvOSUITestsLaunchTests.swift, PIA VPN.xcodeproj/project.pbxproj, PIA-VPN_E2E_Tests/PIA-VPN-e2e-simulator.xctestplan
**Summary**
This PR creates a basic tvOS target with a single screen
=> PIA-845: Create basic target for tvOS

PIA VPN.xcodeproj/project.pbxproj, PIA-VPN_E2E_Tests/Screens/HomeScreen.swift, PIA-VPN_E2E_Tests/Tests/ServerConnectionTests.swift
=> PIA-909: Server Connection Tests

PIA VPN/ar.lproj/Localizable.strings, PIA VPN/da.lproj/Localizable.strings, PIA VPN/de.lproj/Localizable.strings, PIA VPN/es-MX.lproj/Localizable.strings, PIA VPN/fr.lproj/Localizable.strings, PIA VPN/it.lproj/Localizable.strings, PIA VPN/ja.lproj/Localizable.strings, PIA VPN/ko.lproj/Localizable.strings, PIA VPN/nb.lproj/Localizable.strings, PIA VPN/nl.lproj/Localizable.strings, PIA VPN/pl.lproj/Localizable.strings, PIA VPN/pt-BR.lproj/Localizable.strings, PIA VPN/ru.lproj/Localizable.strings, PIA VPN/th.lproj/Localizable.strings, PIA VPN/tr.lproj/Localizable.strings, PIA VPN/zh-Hans.lproj/Localizable.strings, PIA VPN/zh-Hant.lproj/Localizable.strings
This PR updates the translations with the latest updates.
=> PIA-958: Add translations

PIA VPN.xcodeproj/project.pbxproj
=> Release 3.23.6: Increase version number

.github/workflows/development_build.yml, .github/workflows/testflight_deploy.yml
- Enable running the following 2 workflows in parallel when merging to master:
testFlight_deploy
development_build
=> PIA-000: Enable concurrent workflows on push to master

PIA VPN.xcodeproj/project.pbxproj
=> PIA-1161: Update app version to 3.23.7

PIA VPN-tvOS/Dashboard/CompositionRoot/DashboardFactory.swift, PIA VPN-tvOS/Dashboard/Presentation/DashboardViewModel.swift, PIA VPN-tvOS/Dashboard/UI/DashboardView.swift, PIA VPN-tvOS/Navigation/AppRouter.swift, PIA VPN-tvOS/Navigation/CompositionRoot/AppRouterFactory.swift, PIA VPN-tvOS/Navigation/Destinations.swift, PIA VPN-tvOS/RegionsSelection/CompositionRoot/RegionsSelectionFactory.swift, PIA VPN-tvOS/RegionsSelection/Presentation/RegionsListViewModel.swift, PIA VPN-tvOS/RegionsSelection/UI/RegionsListView.swift, PIA VPN-tvOS/RegionsSelection/UseCases/RegionsListUseCase.swift, PIA VPN-tvOS/RootContainer/Presentation/RootContainerViewModel.swift, PIA VPN-tvOS/RootContainer/UI/RootContainerView.swift, PIA VPN-tvOS/RootContainer/UserActivatedContainer/CompositionRoot/UserActivatedContainerFactory.swift, PIA VPN-tvOS/RootContainer/UserActivatedContainer/UI/UserActivatedContainerView.swift, PIA VPN-tvOSTests/Dashboard/DashboardViewModelTests.swift, PIA VPN-tvOSTests/RootContainer/RootContainerViewModelTests.swift, PIA VPN.xcodeproj/project.pbxproj
This PR contains:
- The Navigation from the Dashboard to the Regions list -> Added a unit test to verify this on the `DashboardViewModelTests`
- Basic UI in the form of a grid that shows the list of all the available regions to connect to
=> PIA-1000: Regions list

PIA VPN-tvOS/Dashboard/UI/DashboardView.swift, PIA VPN-tvOS/Login/Presentation/LoginPresentableErrorMapper.swift, PIA VPN-tvOS/Login/UI/LoginView.swift, PIA VPN-tvOS/VPNConfigurationInstalling/Presentation/VPNConfigurationInstallingErrorMapper.swift, PIA VPN-tvOS/VPNConfigurationInstalling/UI/VPNConfigurationInstallingView.swift, PIA VPN.xcodeproj/project.pbxproj
**Summary**
This PR adds current iOS translations to PIA tvOS.
=> PIA-1178: Add tvOS translations

PIA VPN-tvOS/Dashboard/CompositionRoot/DashboardFactory.swift, PIA VPN-tvOS/Dashboard/Presentation/QuickConnectViewModel.swift, PIA VPN-tvOS/Dashboard/UI/QuickConnectView.swift, PIA VPN-tvOS/Dashboard/UseCases/SelectedServerUseCase.swift, PIA VPN-tvOS/Navigation/AppRouter.swift, PIA VPN-tvOS/RegionsSelection/CompositionRoot/RegionsSelectionFactory.swift, PIA VPN-tvOS/RegionsSelection/Presentation/RegionsListViewModel.swift, PIA VPN-tvOS/RegionsSelection/UseCases/RegionsListUseCase.swift, PIA VPN-tvOS/Shared/Utils/PIALibrary+Protocols/ClientPreferences+Protocols.swift, PIA VPN-tvOSTests/Dashboard/QuickConnectViewModelTests.swift, PIA VPN-tvOSTests/RegionsList/Mocks/RegionsListUseCaseMock.swift, PIA VPN-tvOSTests/RegionsList/RegionsListViewModelTests.swift, PIA VPN.xcodeproj/project.pbxproj
- Selection  and connection to the server selected from the Regions List.
- Update the Home Screen with the selected server
- Navigate back to the Home Screen when a server has been selected from the Regions List screen.
=> PIA-1002:  Handle select server from regions list

PIA-VPN_E2E_Tests/Screens/RegionSelectionScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/GeneralSettingsScreen.swift, PIA-VPN_E2E_Tests/Tests/SettingsTests.swift, PIA-VPN_E2E_Tests/Tests/VPNServerListTests.swift
**Summary**
Added Geolocation tests; updated Settings Tests
=> PIA-989: GeoLocations Tests

PIA VPN-tvOS/RootContainer/UI/RootContainerView.swift, PIA VPN-tvOS/VPNConfigurationInstalling/CompositionRoot/InstallVPNConfigurationUseCaseMock.swift, PIA VPN-tvOS/VPNConfigurationInstalling/CompositionRoot/VPNConfigurationInstallingFactory.swift
**Summary**
This PR fixes the navigation to Onboarding VPN installing screen on the simulator.
=> PIA-0000: Update vpn profile installing property enabling for mock

PIA VPN/Tiles/FavoriteServersTile.swift, PIA VPN/Tiles/IPTile.swift, PIA VPN/Tiles/RegionTile.swift, PIA VPN/Tiles/SubscriptionTile.swift, PIA VPN/Tiles/UsageTile.swift, PIA-VPN_E2E_Tests/Screens/Common.swift, PIA-VPN_E2E_Tests/Screens/EditDashboardScreen.swift, PIA-VPN_E2E_Tests/Screens/HomeScreen.swift, PIA-VPN_E2E_Tests/Screens/RegionSelectionScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/SettingsScreen.swift, PIA-VPN_E2E_Tests/Tests/DashboardTests.swift, PIA-VPN_E2E_Tests/Tests/DedicatedIPTests.swift, PIA-VPN_E2E_Tests/Tests/QuickSettingsTests.swift, PIA-VPN_E2E_Tests/Tests/ServerConnectionTests.swift, PIA-VPN_E2E_Tests/Tests/SideMenuTests.swift
**Summary**
Added Dashboard Management Tests; optimised functions
=> PIA-990: Dashboard Management Tests

PIA VPN-tvOSTests/Common/Mocks/AccountProviderTypeMock.swift, PIA VPN-tvOSTests/VPNConfigurationInstalling/Mocks/VpnConfigurationProviderTypeMock.swift
Add missing APIs on mock objects on unit tests
=> PIA-1299: Add missing stubs on unit tests

PIA VPN-tvOS/Bootstraper/BootstraperFactory.swift, PIA VPN-tvOS/Onboarding/CompositionRoot/OnboardingFactory.swift, PIA VPN-tvOS/Onboarding/Data/ConnectionStatsPermisson.swift, PIA VPN-tvOS/Onboarding/Domain/ConnectionStatsPermissonType.swift, PIA VPN-tvOS/RootContainer/Presentation/RootContainerViewModel.swift, PIA VPN-tvOS/RootContainer/UserActivatedContainer/CompositionRoot/UserActivatedContainerFactory.swift, PIA VPN-tvOS/Settings/CompositionRoot/SettingsFactory.swift, PIA VPN-tvOS/Settings/UseCases/LogOutUseCase.swift, PIA VPN-tvOS/Welcome/CompositionRoot/WelcomeFactory.swift, PIA VPN-tvOSTests/RootContainer/Mocks/ConnectionStatsPermissonMock.swift, PIA VPN-tvOSTests/RootContainer/RootContainerViewModelTests.swift, PIA VPN.xcodeproj/project.pbxproj, PIA VPN/SwiftGen+Strings.swift, PIA VPN/en.lproj/Localizable.strings
**Summary**
This PR contains the following:
- Fix navigation problems
- Fix translations
- Setup ServiceQuality
=> PIA-1356: Prepare tvOS version for dogfooding

PIA VPN-tvOS/Dashboard/CompositionRoot/DashboardFactory.swift, PIA VPN-tvOS/Navigation/Presentation/TopNavigationViewModel.swift, PIA VPN-tvOS/Navigation/Routes+Settings.swift, PIA VPN-tvOS/Navigation/UI/TopNavigationView+ViewModifier.swift, PIA VPN-tvOS/RegionsSelection/UI/RegionsContainerView.swift, PIA VPN-tvOS/RootContainer/CompositionRoot/RootContainerFactory.swift, PIA VPN-tvOS/RootContainer/UserActivatedContainer/UI/UserActivatedContainerView.swift, PIA VPN-tvOS/Settings/CompositionRoot/SettingsFactory.swift, PIA VPN-tvOS/Settings/Presentation/AccountSettingsViewModel.swift, PIA VPN-tvOS/Settings/UI/AccountSettingsView.swift, PIA VPN-tvOS/Settings/UI/AvailableSettingsView.swift, PIA VPN-tvOS/Settings/UseCases/LogOutUseCase.swift, PIA VPN-tvOSTests/RegionsList/RegionsDisplayNameUseCaseTests.swift, PIA VPN/SwiftGen+Strings.swift, PIA VPN/en.lproj/Localizable.strings
- Show account information in the account settings
- Update some texts and styles
=> PIA-1300:  Show account information on settings

PIA VPN-tvOS/Dashboard/CompositionRoot/DashboardFactory.swift, PIA VPN-tvOS/Dashboard/Presentation/SelectedServerViewModel.swift, PIA VPN-tvOS/Dashboard/UseCases/SelectedServerUseCase.swift, PIA VPN-tvOS/Navigation/Presentation/TopNavigationViewModel.swift, PIA VPN-tvOS/RegionsSelection/CompositionRoot/RegionsSelectionFactory.swift, PIA VPN-tvOS/RegionsSelection/Presentation/RegionsListViewModel.swift, PIA VPN-tvOS/RegionsSelection/UI/RegionsListItemButton.swift, PIA VPN-tvOS/RegionsSelection/UI/RegionsListView.swift, PIA VPN-tvOS/RegionsSelection/UseCases/OptimalLocationUseCase.swift, PIA VPN-tvOS/RegionsSelection/UseCases/RegionsDisplayNameUseCase.swift, PIA VPN-tvOS/RegionsSelection/UseCases/RegionsFilterUseCase.swift, PIA VPN-tvOS/Settings/UseCases/LogOutUseCase.swift, PIA VPN-tvOSTests/RegionsList/Mocks/OptimalLocationUseCaseMock.swift, PIA VPN-tvOSTests/RegionsList/Mocks/RegionsDisplayNameUseCaseMock.swift, PIA VPN-tvOSTests/RegionsList/OptimalLocationUseCaseTests.swift, PIA VPN-tvOSTests/RegionsList/RegionsDisplayNameUseCaseTests.swift, PIA VPN-tvOSTests/RegionsList/RegionsListViewModelTests.swift, PIA VPN.xcodeproj/project.pbxproj, PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA VPN-tvOS.xcscheme, PIA VPN/AppPreferences.swift, PIA VPN/SwiftGen+Strings.swift, PIA VPN/en.lproj/Localizable.strings
- Also handling displaying the connected server of the Optimal location when the vpn is connected or show "Automatic" when the vpn is not connected
=> PIA-1334: Show Optimal location

PIA VPN.xcodeproj/project.pbxproj, PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA VPN-tvOS.xcscheme, PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA-VPN_tvOS_E2E_Tests.xcscheme, PIA-VPN_tvOS_E2E_Tests/Core/BaseTest.swift, PIA-VPN_tvOS_E2E_Tests/Helpers/ElementHelper.swift, PIA-VPN_tvOS_E2E_Tests/Helpers/KeyboardNavigator.swift, PIA-VPN_tvOS_E2E_Tests/Screens/Common.swift, PIA-VPN_tvOS_E2E_Tests/Screens/DashboardScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/OnboardingScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SettingsScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SignInScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/WelcomeScreen.swift, PIA-VPN_tvOS_E2E_Tests/Tests/SignInTests.swift, PIA-VPN_tvOS_E2E_Tests/Util/CredentialsUtil.swift
**Summary**
Base Framework for the tvOS E2E Tests + Sign In Tests
=> PIA-1346: tvOS E2E Test Framework POC

PIA VPN.xcodeproj/project.pbxproj, PIA-VPN_tvOS_E2E_Tests/Screens/DashboardScreen.swift, PIA-VPN_tvOS_E2E_Tests/Tests/OnboardingTests.swift
**Summary**
Added Onboarding Tests
=> PIA-1423: Onboarding Tests

PIA VPN-tvOS/Bootstraper/BootstraperFactory.swift, PIA VPN-tvOS/Bootstrapper.swift, PIA VPN-tvOS/Help/CompositionRoot/HelpFactory.swift, PIA VPN-tvOS/Help/Presentation/AboutOptionsViewModel.swift, PIA VPN-tvOS/Help/Presentation/AcknowledgementsViewModel.swift, PIA VPN-tvOS/Help/UI/AcknowledgementsView.swift, PIA VPN-tvOS/Help/UseCases/LicensesUseCase.swift, PIA VPN-tvOS/Navigation/CompositionRoot/TopNavigationFactory.swift, PIA VPN-tvOS/Navigation/Presentation/TopNavigationViewModel.swift, PIA VPN-tvOS/Navigation/Routes+HelpSettings.swift, PIA VPN-tvOS/Navigation/UI/TopNavigationView.swift, PIA VPN-tvOS/Resources/Licences.plist, PIA VPN-tvOS/RootContainer/CompositionRoot/RootContainerFactory.swift, PIA VPN-tvOS/RootContainer/Presentation/RootContainerViewModel.swift, PIA VPN-tvOS/Settings/UI/AvailableSettingsView.swift, PIA VPN-tvOS/Shared/StateMonitors/ConnectionStateMonitor.swift, PIA VPN-tvOSTests/Common/ConnectionStateMonitorTests.swift, PIA VPN-tvOSTests/Common/Mocks/ConnectionStateMonitorMock.swift, PIA VPN-tvOSTests/HelpOptions/LicensesUseCaseTests.swift, PIA VPN-tvOSTests/RootContainer/RootContainerViewModelTests.swift, PIA VPN-tvOSTests/Shared/LeadingNavigationBarViewModel.swift, PIA VPN-tvOSTests/Shared/Mocks/URLSessionMock.swift, PIA VPN.xcodeproj/project.pbxproj, PIA VPN/AboutComponent.swift, PIA VPN/SwiftGen+Strings.swift, PIA VPN/en.lproj/Localizable.strings
- Show the Acknowledgments under the Help Options.
- Handle getting the content of each license async and cache it if needed
- This PR also fixes a race condition on the selected section of the top navigation bar that was leaving the Settings button without highlighting state when changing the focus between the leading top navigation items and the training navigation items
=> PIA-1375: Acknowledgements screen

PIA VPN.xcodeproj/project.pbxproj, PIA VPN/SwiftGen+Strings.swift, PIA VPN/en.lproj/Localizable.strings
**Summary**
This PR adds all the text needed for tvOS screens
=> PIA-1301: Add localisation keys for tvOS

PIA VPN.xcodeproj/project.pbxproj, PIA-VPN_E2E_Tests/Screens/Common.swift, PIA-VPN_E2E_Tests/Screens/DedicatedIPScreen.swift, PIA-VPN_E2E_Tests/Screens/HomeScreen.swift, PIA-VPN_E2E_Tests/Screens/LoginScreen.swift, PIA-VPN_E2E_Tests/Screens/RegionSelectionScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/AutomationSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/GeneralSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/HelpSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/PrivacySettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/ProtocolsSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/QuickSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/SettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/SideMenuScreen.swift, PIA-VPN_E2E_Tests/Screens/VPNPermissionScreen.swift, PIA-VPN_E2E_Tests/Tests/DedicatedIPTests.swift, PIA-VPN_E2E_Tests/Tests/QuickSettingsTests.swift, PIA-VPN_E2E_Tests/Tests/SettingsTests.swift, PIA-VPN_E2E_Tests/Tests/VPNServerListTests.swift, PIA-VPN_tvOS_E2E_Tests/Screens/DashboardScreen.swift, PIA-VPN_tvOS_E2E_Tests/Tests/OnboardingTests.swift
**Summary**
Optimised iOS E2E tests
=> PIA-1459 Optimise Tests

PIA VPN-tvOS/RegionsSelection/UseCases/RegionsFilterUseCase.swift, PIA VPN-tvOSTests/RegionsList/RegionsFilterUseCaseTests.swift
Enhance search functionality:
- To handle multiple words on search term
- To match the beginning of any word from the server name with the search term
=> PIA-1435: Enhance search functionality

PIA VPN-tvOS/CompositionRoot/LoginQRFactory.swift, PIA VPN-tvOS/Domain/Entities/LoginQRCode.swift, PIA VPN-tvOS/Domain/Use cases/GenerateLoginQRCodeUseCase.swift, PIA VPN-tvOS/Domain/Use cases/ValidateLoginQRCodeUseCase.swift, PIA VPN-tvOS/LoginQR/LoginQRContainerView.swift, PIA VPN-tvOS/LoginQR/LoginQRExpiredView.swift, PIA VPN-tvOS/LoginQR/LoginQRView.swift, PIA VPN-tvOS/Navigation/Routes+Onboarding.swift, PIA VPN-tvOS/Presentation/LoginQRViewModel.swift, PIA VPN-tvOS/Welcome/CompositionRoot/WelcomeFactory.swift, PIA VPN.xcodeproj/project.pbxproj, PIA VPN/SwiftGen+Strings.swift, PIA VPN/en.lproj/Localizable.strings
**Summary**
This PR contains the UI and Presentation layers for Sign in with QR on tvOS.
The services and tests will be added in another PR.
=> PIA-1436: Add LoginQRCode screen for tvOS

PIA VPN.xcodeproj/project.pbxproj, PIA-VPN_E2E_Tests.xctestplan, PIA-VPN_E2E_Tests/Screens/Settings/HelpSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/PrivacySettingsScreen.swift, PIA-VPN_E2E_Tests/Tests/SettingsTests.swift, PIA-VPN_tvOS_E2E_Tests/Core/BaseTest.swift, PIA-VPN_tvOS_E2E_Tests/Helpers/ElementHelper.swift, PIA-VPN_tvOS_E2E_Tests/Helpers/KeyboardNavigator.swift, PIA-VPN_tvOS_E2E_Tests/Helpers/WaitHelper.swift, PIA-VPN_tvOS_E2E_Tests/Screens/Common.swift, PIA-VPN_tvOS_E2E_Tests/Screens/DashboardScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/LocationSelectionScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/OnboardingScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SettingsScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SignInScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/WelcomeScreen.swift, PIA-VPN_tvOS_E2E_Tests/Tests/LocationSelectionTests.swift
**Summary**
PIA-1514: Added Location Selection Tests to tvOS, Optimised KeyboardNavigator and MoveFocus, Optimised iOS Tests
=> PIA-1514: Location Selection Tests for tvOS

PIA VPN-tvOS/Shared/CompositionRoot/VpnConnectionFactory.swift, PIA VPN-tvOS/Shared/StateMonitors/StateMonitorsFactory.swift, PIA VPN-tvOS/Shared/Utils/PIALibrary+Protocols/PIALibrary+Protocols.swift
- This enables us to use the simulator for demo purposes and e2e tests around the connection flow
=> PIA-1492: Enable mock connection on tvOS simulator

PIA-VPN_E2E_Tests/Core/BaseTest.swift, PIA-VPN_E2E_Tests/Helpers/WaitHelper.swift, PIA-VPN_E2E_Tests/Screens/DedicatedIPScreen.swift, PIA-VPN_E2E_Tests/Screens/EditDashboardScreen.swift, PIA-VPN_E2E_Tests/Screens/HomeScreen.swift, PIA-VPN_E2E_Tests/Screens/LoginScreen.swift, PIA-VPN_E2E_Tests/Screens/RegionSelectionScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/AutomationSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/GeneralSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/HelpSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/PrivacySettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/ProtocolsSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/QuickSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/SettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/SideMenuScreen.swift, PIA-VPN_E2E_Tests/Screens/VPNPermissionScreen.swift, PIA-VPN_E2E_Tests/Screens/WelcomeScreen.swift, PIA-VPN_E2E_Tests/Tests/OnboardingTests.swift, PIA-VPN_tvOS_E2E_Tests/Core/BaseTest.swift, PIA-VPN_tvOS_E2E_Tests/Helpers/ElementHelper.swift, PIA-VPN_tvOS_E2E_Tests/Screens/Common.swift, PIA-VPN_tvOS_E2E_Tests/Screens/DashboardScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/LocationSelectionScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SettingsScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SignInScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/WelcomeScreen.swift, PIA-VPN_tvOS_E2E_Tests/Tests/LocationSelectionTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/OnboardingTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/SignInTests.swift
**Summary**
Favourite Tests; ios/tvos method optimisation
=> PIA-1535: Favourite Tests

Resources/staging.endpoint
**Summary**
This PR adds staging url to PIA
=> PIA-1599: Add staging url

PIA VPN.xcodeproj/project.pbxproj, PIA-VPN_E2E_Tests/Util/CredentialsUtil.swift, PIA-VPN_tvOS_E2E_Tests/Screens/Common.swift, PIA-VPN_tvOS_E2E_Tests/Screens/DashboardScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/DedicatedIPScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/LocationSelectionScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SettingsScreen.swift, PIA-VPN_tvOS_E2E_Tests/Tests/DedicatedIPTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/LocationSelectionTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/OnboardingTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/SignInTests.swift, PIA-VPN_tvOS_E2E_Tests/Util/CredentialsUtil.swift, PIA-VPN_tvOS_E2E_Tests/Util/DedicatedIPUtil.swift
**Summary**
Added Dedicated IP Tests
=> PIA-1604: Dedicated IP Tests

PIA VPN.xcodeproj/project.pbxproj, PIA-VPN_tvOS_E2E_Tests/Core/BaseTest.swift, PIA-VPN_tvOS_E2E_Tests/Helpers/ElementHelper.swift, PIA-VPN_tvOS_E2E_Tests/Screens/DashboardScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/HelpScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/LocationSelectionScreen.swift, PIA-VPN_tvOS_E2E_Tests/Tests/HelpTests.swift
=> PIA-1634: Help Tests

PIA VPN.xcodeproj/project.pbxproj, PIA-VPN_E2E_Tests/Core/BaseTest.swift, PIA-VPN_E2E_Tests/Screens/Common.swift, PIA-VPN_E2E_Tests/Screens/DedicatedIPScreen.swift, PIA-VPN_E2E_Tests/Screens/EditDashboardScreen.swift, PIA-VPN_E2E_Tests/Screens/HomeScreen.swift, PIA-VPN_E2E_Tests/Screens/LoginScreen.swift, PIA-VPN_E2E_Tests/Screens/RegionSelectionScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/AutomationSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/GeneralSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/HelpSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/PrivacySettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/ProtocolsSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/QuickSettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/Settings/SettingsScreen.swift, PIA-VPN_E2E_Tests/Screens/SideMenuScreen.swift, PIA-VPN_E2E_Tests/Screens/VPNPermissionScreen.swift, PIA-VPN_E2E_Tests/Screens/WelcomeScreen.swift, PIA-VPN_tvOS_E2E_Tests/Core/BaseTest.swift, PIA-VPN_tvOS_E2E_Tests/Screens/Common.swift, PIA-VPN_tvOS_E2E_Tests/Screens/DashboardScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/DedicatedIPScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/HelpScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/LocationSelectionScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/OnboardingScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SettingsScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SignInScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/WelcomeScreen.swift
**Summary**
enhanced tests to avoid hardcoded english identifiers by using localisations
=> PIA-991: ios and tvos tests to update to use localisations

.github/workflows/ios_testflight_deploy.yml, PIA VPN.xcodeproj/project.pbxproj
- Integrate NWConnection for http requests on WireGuard library
- Update app version
- Build iOS app with Xcode 15
=> PIA-1588: Build iOS app with XCode 15

.github/workflows/development_build.yml
- Update CI workflow to build development ipa from Xcode 15
=> PIA-922: Build developer ipa from XCode 15

.github/workflows/ios_testflight_deploy.yml, fastlane/Fastfile
**Summary**
This PR adds the production build to the artifacts on GHA when the build is ready to be uploaded to Testflight.
=> PIA-0000: Add Testflight ipa to artifacts

.github/workflows/ios_testflight_deploy.yml
**Summary**
This PR creates the artifacts directory before building the ipa
=> PIA-0000: Make sure artifacts dir exists before moving ipa

PIA VPN-tvOS/Signup/Data/DecoratorPurchaseProductsProvider.swift, PIA VPN-tvOS/Signup/Data/PurchaseProductDomainErrorMapper.swift, PIA VPN-tvOS/Signup/Domain/Entities/PurchaseProductsError.swift, PIA VPN-tvOS/Signup/Domain/Interfaces/PurchaseProductsProviderType.swift, PIA VPN-tvOS/Signup/Presentation/SignupPresentableErrorMapper.swift, PIA VPN-tvOS/Signup/Presentation/SignupViewModel.swift, PIA VPN-tvOS/Signup/UI/SignupView.swift, PIA VPN-tvOS/SignupEmail/CompositionRoot/SignupEmailFactory.swift, PIA VPN-tvOS/SignupEmail/Data/SignupDomainErrorMapper.swift, PIA VPN-tvOS/SignupEmail/Data/SignupProvider.swift, PIA VPN-tvOS/SignupEmail/Domain/Entities/SignupError.swift, PIA VPN-tvOS/SignupEmail/Domain/Interfaces/SignupProviderType.swift, PIA VPN-tvOS/SignupEmail/Presentation/SignupEmailViewModel.swift, PIA VPN-tvOS/SignupEmail/UI/SignupEmailView.swift, PIA VPN-tvOSTests/Signup/Data/DecoratorPurchaseProductsProviderTests.swift, PIA VPN-tvOSTests/Signup/Data/SignupProviderTests.swift, PIA VPN-tvOSTests/Signup/Domain/PurchaseProductUseCaseTests.swift, PIA VPN-tvOSTests/Signup/Domain/SignupUseCaseTests.swift, PIA VPN-tvOSTests/Signup/Integration/SignupEmailIntegrationTests.swift, PIA VPN-tvOSTests/Signup/Integration/SignupIntegrationTests.swift, PIA VPN-tvOSTests/Signup/Mocks/PurchaseProductsProviderMock.swift, PIA VPN-tvOSTests/Signup/Mocks/SignupProviderMock.swift, PIA VPN-tvOSTests/Signup/Presentation/SignupEmailViewModelTests.swift, PIA VPN-tvOSTests/Signup/Presentation/SignupViewModelTests.swift, PIA VPN.xcodeproj/project.pbxproj, PIA VPN/SwiftGen+Strings.swift, PIA VPN/en.lproj/Localizable.strings
**Summary**
This PR adds error handling logic to Sign up feature for tvOS
=> PIA-1775: Add error handling logic for tvOS signup

PIA VPN.xcodeproj/project.pbxproj, PIA VPN/DashboardViewController.swift
- Update PIALibrary to latest WG Xcode 15 integration
- Fix UI glitches while connecting/reconnecting on poor network conditions
- Update App version to 3.24.3
=> PIA-1764: WG on Xcode 15 integration

PIA VPN.xcodeproj/project.pbxproj, PIA VPN/AboutViewController.swift, PIA VPN/AccountViewController.swift, PIA VPN/DashboardViewController.swift, PIA VPN/DedicatedIpViewController.swift, PIA VPN/Info.plist, PIA VPN/OptionsViewController.swift, PIA VPN/RegionsViewController.swift, PIA VPN/SettingsViewController.swift, PIA VPN/ShowConnectionStatsViewController.swift, PIA VPN/UserInterface.swift
- Fix UI glitches when the iPhone switches from landscape to portrait when compiled with Xcode 15
=> PIA-1793: Fix UI glitches when switching device orientation 

PIA VPN-tvOS/LoginQR/UI/LoginQRContainerView.swift, PIA VPN-tvOS/Navigation/AppRouter.swift, PIA VPN-tvOS/Navigation/Routes+Onboarding.swift, PIA VPN-tvOS/Signup/CompositionRoot/SignupFactory.swift, PIA VPN-tvOS/Signup/UI/SignupTermsView.swift, PIA VPN.xcodeproj/project.pbxproj, PIA VPN/SwiftGen+Strings.swift, PIA VPN/en.lproj/Localizable.strings
**Summary**
This PR adds the screens for Privacy policy and Terms&Conditions on the Sign up flow for tvOS
=> PIA-1813: Add terms and privacy to signup feature on tvOS

PIA VPN-tvOS/Login/CompositionRoot/LoginFactory.swift, PIA VPN-tvOS/Login/Data/LoginProvider.swift, PIA VPN-tvOS/Login/Domain/Interfaces/LoginProviderType.swift, PIA VPN-tvOS/LoginQR/CompositionRoot/LoginQRFactory.swift, PIA VPN-tvOS/LoginQR/Data/PaymentProvider.swift, PIA VPN-tvOS/LoginQR/Domain/Interfaces/PaymentProviderType.swift, PIA VPN-tvOS/LoginQR/Domain/Use cases/LoginWithReceiptUseCase.swift, PIA VPN-tvOS/LoginQR/Presentation/LoginQRViewModel.swift, PIA VPN-tvOS/LoginQR/UI/LoginQRContainerView.swift, PIA VPN-tvOS/LoginQR/UI/LoginQRView.swift, PIA VPN-tvOS/Navigation/Routes+Onboarding.swift, PIA VPN-tvOSTests/Login/Helpers/AccountProviderMock.swift, PIA VPN-tvOSTests/Login/Helpers/LoginProviderMock.swift, PIA VPN-tvOSTests/Login/LoginProviderTests.swift, PIA VPN-tvOSTests/LoginQR/LoginQRViewModelTests.swift, PIA VPN-tvOSTests/LoginQR/LoginWithReceiptUseCaseTests.swift, PIA VPN-tvOSTests/LoginQR/Mocks/LoginWithReceiptUseCaseMock.swift, PIA VPN-tvOSTests/LoginQR/Mocks/PaymentProviderMock.swift, PIA VPN.xcodeproj/project.pbxproj
**Summary**
This PR adds the recover purchases feature for tvOS, so users can sign in with an existing receipt.
=> PIA-1824: Recover purchases sign in tvOS

PIA VPN/ar.lproj/Localizable.strings, PIA VPN/da.lproj/Localizable.strings, PIA VPN/de.lproj/Localizable.strings, PIA VPN/es-MX.lproj/Localizable.strings, PIA VPN/fr.lproj/Localizable.strings, PIA VPN/it.lproj/Localizable.strings, PIA VPN/ja.lproj/Localizable.strings, PIA VPN/ko.lproj/Localizable.strings, PIA VPN/nb.lproj/Localizable.strings, PIA VPN/nl.lproj/Localizable.strings, PIA VPN/pl.lproj/Localizable.strings, PIA VPN/pt-BR.lproj/Localizable.strings, PIA VPN/ru.lproj/Localizable.strings, PIA VPN/th.lproj/Localizable.strings, PIA VPN/tr.lproj/InfoPlist.strings, PIA VPN/tr.lproj/Localizable.strings, PIA VPN/zh-Hans.lproj/Localizable.strings, PIA VPN/zh-Hant.lproj/Localizable.strings
**Summary**
This PR adds the translations for tvOS.
=> PIA-1630: Add translations for tvOS

.github/workflows/ios_pull_request.yml, .github/workflows/ios_testflight_deploy.yml, .github/workflows/tvos_pull_request.yml, .github/workflows/tvos_testflight_deploy.yml
**Summary**
Downgrade XCode to 15.0.1 so E2E tests can pass until we fix them on new versions.
=> PIA-1864: Downgrade to 15.0.1

PIA VPN.xcodeproj/project.pbxproj, PIA-VPN_tvOS_E2E_Tests.xctestplan, PIA-VPN_tvOS_E2E_Tests/Core/BaseTest.swift, PIA-VPN_tvOS_E2E_Tests/Screens/SignUpScreen.swift, PIA-VPN_tvOS_E2E_Tests/Screens/WelcomeScreen.swift, PIA-VPN_tvOS_E2E_Tests/Tests/ConnectionTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/DedicatedIPTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/HelpTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/LocationSelectionTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/OnboardingTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/SignInTests.swift, PIA-VPN_tvOS_E2E_Tests/Tests/SignUpTests.swift
**Summary**
Added Sign Up Tests
Updated Base Test - used flags to identify which tests start from signed-in state and which ones to start from logged out state
=> PIA-1860: SignUpTests

.github/workflows/development_build.yml, PIA VPN-tvOSTests/Signup/Mocks/SignupUseCaseMock.swift, PIA VPN.xcodeproj/project.pbxproj, fastlane/Fastfile
- Update `PIALibrary` 
- Bump app version
- Build a development artifact that can connect to staging (for testing purposes)
=> KM-4542: Update dependencies

PIA VPN.xcodeproj/project.pbxproj
- Update to latest `master` release of PIALibrary
=> KM-4542: Update PIALibrary

PIA VPN.xcodeproj/project.pbxproj
- Update `PIALibrary` to latest revision from `master`
=> KM-4542: Update PIA library revision to af6891d

PIA VPN.xcodeproj/project.pbxproj
=> KM-4542: Update PIALibrary to e864a59

PIA VPN.xcodeproj/project.pbxproj
**Summary**
This PR bumps PIALibrary to include the endpoints order change for meta ips.
=> Bump PIALibrary

PIA VPN.xcodeproj/project.pbxproj
=> iIncrease version to 2.25.2

PIA VPN/ForceUpdateViewController.swift, PIA VPN/ForceUpdateViewController.xib, PIA VPN/SwiftGen+Strings.swift, PIA VPN/en.lproj/Localizable.strings
**Summary**
This PR adds a new text to Force update screen when VPN is connected
=> KM-5043: Add strings for force update when VPN is connected

.github/workflows/development_build.yml, .github/workflows/ios_pull_request.yml, .github/workflows/ios_testflight_deploy.yml, .github/workflows/tvos_pull_request.yml, .github/workflows/tvos_testflight_deploy.yml, PIA VPN/BorderedTextField.swift
- Update project to compile with Xcode 16
- Update CI config to run on Xcode 16
=> KM-8019: Update to Xcode 16

PIA VPN-tvOS/LoginQR/CompositionRoot/LoginQRFactory.swift, PIA VPN-tvOS/LoginQR/Data/LoginQRProvider.swift, PIA VPN-tvOS/LoginQR/Domain/Interfaces/ValidateLoginQRCodeProviderType.swift, PIA VPN-tvOS/LoginQR/Domain/Use cases/ValidateLoginQRCodeUseCase.swift, PIA VPN-tvOSTests/Login/Helpers/AccountProviderMock.swift, PIA VPN-tvOSTests/LoginQR/LoginQRProviderTests.swift, PIA VPN-tvOSTests/LoginQR/Mocks/GenerateQRLoginUseCaseMock.swift, PIA VPN-tvOSTests/LoginQR/Mocks/ValidateLoginQRCodeProviderMock.swift, PIA VPN-tvOSTests/LoginQR/ValidateLoginQRCodeUseCaseTests.swift, PIA VPN.xcodeproj/project.pbxproj
**Summary**
[Jira ticket](https://polymoon.atlassian.net/browse/KM-8127)
Fixes #
=> KM-8127: Fix QR sign in tvos

PIA VPN.xcodeproj/project.pbxproj
A similar PR may already be submitted!
Please search among the Pull requests before creating one.
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
For more information, see the [CONTRIBUTING](/.github.com/CONTRIBUTING.md) readme or the contributing [guide](https://pia-oss.github.io/contribute).
**Summary**
Fixes #
=> Bump up PIALibrary
