- PIA VPN-tvOS/Login/CompositionRoot/LoginFactory.swift
- PIA VPN-tvOS/Login/Data/LoginDomainErrorMapper.swift
- PIA VPN-tvOS/Login/Data/LoginProvider.swift
- PIA VPN-tvOS/Login/Data/UserAccountMapper.swift
- PIA VPN-tvOS/Login/Domain/Entities/AccountInfo.swift
- PIA VPN-tvOS/Login/Domain/Entities/Credentials.swift
- PIA VPN-tvOS/Login/Domain/Entities/LoginError.swift
- PIA VPN-tvOS/Login/Domain/Entities/UserAccount.swift
- PIA VPN-tvOS/Login/Domain/Interfaces/LoginDomainErrorMapperType.swift
- PIA VPN-tvOS/Login/Domain/Interfaces/LoginProviderType.swift
- PIA VPN-tvOS/Login/Domain/Use cases/LoginWithCredentialsUseCase.swift
- PIA VPN-tvOS/Login/Presentation/CheckLoginAvailability.swift
- PIA VPN-tvOS/Login/Presentation/LoginPresentableErrorMapper.swift
- PIA VPN-tvOS/Login/Presentation/LoginViewModel.swift
- PIA VPN-tvOS/Login/Presentation/ValidateCredentialsFormat.swift
- PIA VPN-tvOS/Login/UI/LoginView.swift
- PIA VPN-tvOS/Login/Utils/Foundation+PIA.swift
- PIA VPN-tvOS/PIA_VPN_tvOSApp.swift
- PIA VPN-tvOSTests/Login/CheckLoginAvailabilityTests.swift
- PIA VPN-tvOSTests/Login/Helpers/AccountProviderMock.swift
- PIA VPN-tvOSTests/Login/Helpers/CheckLoginAvailabilityMock.swift
- PIA VPN-tvOSTests/Login/Helpers/Equatable.swift
- PIA VPN-tvOSTests/Login/Helpers/LoginProviderMock.swift
- PIA VPN-tvOSTests/Login/Helpers/LoginWithCredentialsUseCaseMock.swift
- PIA VPN-tvOSTests/Login/Helpers/Stubs.swift
- PIA VPN-tvOSTests/Login/LoginIntegrationTests.swift
- PIA VPN-tvOSTests/Login/LoginViewModelTests.swift
- PIA VPN-tvOSTests/Login/LoginWithCredentialsUseCaseTests.swift
- PIA VPN.xcodeproj/project.pbxproj
This PR adds the Login screen to PIA tvOS. It includes all the different layers involved:
- UI
- Data
- Presentation
- Domain/App logic
- Composition Root
`LoginViewModel` exposes a status property in order to validate the logic when unit testing since the screen does not navigate when the operations was successful. This property will be taken care of once we tackle the navigation to the next screen. 
Tests are composed mainly by unit tests. There are also a couple of integration tests that are mocking the login provider which is a bridge to PIALibrary's `DefaultAccountProvider`. These tests are responsible of testing the integration between the all the different components on presentation and domain layers.
Error handling and proper design will be tackled in a different PR.
> PIA-882: Login feature for tvOS

- PIA VPN-tvOS/Dashboard/CompositionRoot/DashboardFactory.swift
- PIA VPN-tvOS/Dashboard/Presentation/PIAConnectionButtonViewModel.swift
- PIA VPN-tvOS/Dashboard/UI/DashboardView.swift
- PIA VPN-tvOS/Dashboard/UI/PIAConnectionButton.swift
- PIA VPN-tvOS/Dashboard/UseCases/VpnConnectionUseCase.swift
- PIA VPN-tvOS/PIA VPN-tvOS.entitlements
- PIA VPN-tvOS/PIA_VPN_tvOSApp.swift
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/Contents.json
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/app_background.colorset/Contents.json
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/pia_connect_button_grey.colorset/Contents.json
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/pia_green.colorset/Contents.json
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/pia_green_dark_20.colorset/Contents.json
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/pia_green_dark_50.colorset/Contents.json
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/pia_red.colorset/Contents.json
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/pia_red_dark.colorset/Contents.json
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/pia_yellow.colorset/Contents.json
- PIA VPN-tvOS/Shared/UI/Colors.xcassets/pia_yellow_dark.colorset/Contents.json
- PIA VPN-tvOS/Shared/UI/PIA+Animation.swift
- PIA VPN-tvOS/Shared/UI/PIAColors+SwitUI.swift
- PIA VPN-tvOSTests/Dashboard/Mocks/VpnConnectionUseCaseTypeMock.swift
- PIA VPN-tvOSTests/Dashboard/PIAConnectionButtonViewModelTests.swift
- PIA VPN.xcodeproj/project.pbxproj
- PIA VPN/Images.xcassets/PIAX/Dashboard/vpn-button.imageset/Contents.json
- PIAWidget/Assets.xcassets/vpn-button.imageset/Contents.json
- Dashboard View with connect button
- The button has some basic animation for transitioning between the different Vpn States
- Added Unit tests on the ViewModel of the Connection Button
> PIA-885: Dashboard connect button UI

- PIA VPN.xcodeproj/project.pbxproj
- PIA VPN/Settings/SettingPopoverSelectionView.swift
- PIA VPN/Tiles/ConnectionTileCollectionViewCell.swift
- PIA VPN/Tiles/FavoriteServersTileCollectionViewCell.swift
- PIA VPN/Tiles/IPTileCollectionViewCell.swift
- PIA VPN/Tiles/QuickConnectTileCollectionViewCell.swift
- PIA VPN/Tiles/SubscriptionTileCollectionViewCell.swift
- PIA VPN/Tiles/UsageTileCollectionViewCell.swift
- PIA-VPN_E2E_Tests/Helpers/ElementHelper.swift
- PIA-VPN_E2E_Tests/Screens/EditDashboardScreen.swift
- PIA-VPN_E2E_Tests/Screens/HomeScreen.swift
- PIA-VPN_E2E_Tests/Screens/LoginScreen.swift
- PIA-VPN_E2E_Tests/Screens/RegionSelectionScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/HelpSettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/ProtocolsSettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/QuickSettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/SettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/VPNPermissionScreen.swift
- PIA-VPN_E2E_Tests/Screens/WelcomeScreen.swift
- PIA-VPN_E2E_Tests/Tests/DashboardTests.swift
- PIA-VPN_E2E_Tests/Tests/ServerConnectionTests.swift
Added Dashboard Connection Details Tests; Optimised elements and methods on test screen classes
> PIA-986: Dashboard Connection Details Tests

- .github/workflows/development_build.yml
- fastlane/Fastfile
- This PR sets up a CI workflow to build an `ipa` artifact with Development credentials every time we merge to `master`
- The Development build can only be installed on devices that are authorized on our Apple Developer portal
> PIA-000: Add workflow to archive a development build

- PIA VPN-tvOS/RootContainer/Presentation/RootContainerViewModel.swift
- PIA VPN-tvOS/RootContainer/UI/RootContainerView.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/CompositionRoot/VPNConfigurationInstallingFactory.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Data/InstallVpnConfigurationProvider.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Data/VPNConfigurationAvailability.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Data/VpnConfigurationProviderType.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Domain/Entities/InstallVPNConfigurationError.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Domain/Interfaces/InstallVPNConfigurationUseCase.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Domain/Interfaces/VPNConfigurationAvailabilityType.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Presentation/VPNConfigurationInstallingErrorMapper.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Presentation/VPNConfigurationInstallingStatus.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Presentation/VPNConfigurationInstallingViewModel.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/UI/VPNConfigurationInstallingView.swift
- PIA VPN-tvOSTests/VPNConfigurationInstalling/InstallVpnConfigurationProviderTests.swift
- PIA VPN-tvOSTests/VPNConfigurationInstalling/Mocks/InstallVPNConfigurationUseCaseMock.swift
- PIA VPN-tvOSTests/VPNConfigurationInstalling/Mocks/VPNConfigurationAvailabilityMock.swift
- PIA VPN-tvOSTests/VPNConfigurationInstalling/Mocks/VpnConfigurationProviderTypeMock.swift
- PIA VPN-tvOSTests/VPNConfigurationInstalling/VPNConfigurationInstallingViewModelTests.swift
- PIA VPN.xcodeproj/project.pbxproj
**Summary**
This PR adds the VPNConfiguration profile installation for tvOS.
It contains the functionality and also some unit tests to verify the behaviour.
> PIA-888:  VPNConfiguration profile installation 

- .github/workflows/pull_request.yml
- PIA VPN.xcodeproj/project.pbxproj
- PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA-VPN_E2E_Tests.xcscheme
- PIA VPN/DedicatedIpRowViewCell.swift
- PIA-VPN_E2E_Tests/Screens/DedicatedIPScreen.swift
- PIA-VPN_E2E_Tests/Screens/EditDashboardScreen.swift
- PIA-VPN_E2E_Tests/Screens/HomeScreen.swift
- PIA-VPN_E2E_Tests/Screens/LoginScreen.swift
- PIA-VPN_E2E_Tests/Screens/RegionSelectionScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/AutomationSettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/GeneralSettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/HelpSettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/PrivacySettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/ProtocolsSettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/Settings/SettingsScreen.swift
- PIA-VPN_E2E_Tests/Screens/SideMenuScreen.swift
- PIA-VPN_E2E_Tests/Tests/DashboardTests.swift
- PIA-VPN_E2E_Tests/Tests/DedicatedIPTests.swift
- PIA-VPN_E2E_Tests/Tests/QuickSettingsTests.swift
- PIA-VPN_E2E_Tests/Tests/ServerConnectionTests.swift
- PIA-VPN_E2E_Tests/Tests/SettingsTests.swift
- PIA-VPN_E2E_Tests/Util/DedicatedIPUtil.swift
Added Dedicated IP Tests; 
Optimised elements and methods on test screen classes;
Added Dedicated IP Token on env variables
> PIA-988: Dedicated IP Tests

- PIA VPN.xcodeproj/project.pbxproj
- PIA-VPN_E2E_Tests/Screens/RegionSelectionScreen.swift
- PIA-VPN_E2E_Tests/Screens/SideMenuScreen.swift
- PIA-VPN_E2E_Tests/Tests/SideMenuTests.swift
> PIA-987: Side Menu Tests

- PIA VPN-tvOS/Dashboard/CompositionRoot/DashboardFactory.swift
- PIA VPN-tvOS/Dashboard/Presentation/DashboardViewModel.swift
- PIA VPN-tvOS/Login/CompositionRoot/LoginFactory.swift
- PIA VPN-tvOS/Login/Presentation/LoginViewModel.swift
- PIA VPN-tvOS/Navigation/AppRouter.swift
- PIA VPN-tvOS/Navigation/Routes.swift
- PIA VPN-tvOS/RootContainer/CompositionRoot/RootContainerFactory.swift
- PIA VPN-tvOS/RootContainer/Presentation/RootContainerViewModel.swift
- PIA VPN-tvOS/RootContainer/UI/RootContainerView.swift
- PIA VPN-tvOS/RootContainer/UserActivatedContainer/UI/UserActivatedContainerView.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/CompositionRoot/VPNConfigurationInstallingFactory.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Presentation/VPNConfigurationInstallingViewModel.swift
- PIA VPN-tvOSTests/Common/Mocks/AppRouterSpy.swift
- PIA VPN-tvOSTests/Dashboard/DashboardViewModelTests.swift
- PIA VPN-tvOSTests/Login/LoginIntegrationTests.swift
- PIA VPN-tvOSTests/Login/LoginViewModelTests.swift
- PIA VPN-tvOSTests/RootContainer/RootContainerViewModelTests.swift
- PIA VPN-tvOSTests/VPNConfigurationInstalling/VPNConfigurationInstallingViewModelTests.swift
- PIA VPN.xcodeproj/project.pbxproj
**Summary**
This PR integrates the installing of VPN profile in the App flow.
The approach is based on this [ADR](https://github.com/xvpn/xv_iphone/blob/master/docs/adr/0010-swiftui-navigation.md).
> PIA-1177: Integrate VPN profile installing in App flow

- PIA VPN-tvOS/Dashboard/CompositionRoot/DashboardFactory.swift
- PIA VPN-tvOS/Dashboard/Presentation/PIAConnectionButtonViewModel.swift
- PIA VPN-tvOS/Shared/StateMonitors/VPNStatusMonitor.swift
- PIA VPN-tvOSTests/Common/Mocks/VpnConnectionUseCaseMock.swift
- PIA VPN-tvOSTests/Dashboard/PIAConnectionButtonViewModelTests.swift
- PIA VPN-tvOSTests/Shared/Mocks/VPNStatusMonitorMock.swift
- PIA VPN.xcodeproj/project.pbxproj
**Summary**
This PR integrates the VPN status monitor to update the connection button in Home with the received vpn state.
Unit tests have been also updated.
> PIA-1224: Integrate VPN status monitor into connection button

- PIA VPN-tvOS/Navigation/Destinations.swift
- PIA VPN-tvOS/RegionsSelection/CompositionRoot/RegionsSelectionFactory.swift
- PIA VPN-tvOS/RegionsSelection/Presentation/RegionsContainerViewModel.swift
- PIA VPN-tvOS/RegionsSelection/Presentation/RegionsListViewModel.swift
- PIA VPN-tvOS/RegionsSelection/UI/RegionsContainerView.swift
- PIA VPN-tvOS/RegionsSelection/UI/RegionsListView.swift
- PIA VPN-tvOS/RootContainer/UserActivatedContainer/UI/UserActivatedContainerView.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/CompositionRoot/VPNConfigurationInstallingFactory.swift
- PIA VPN-tvOS/VPNConfigurationInstalling/Data/InstallVpnConfigurationProvider.swift
- PIA VPN-tvOSTests/RegionsList/RegionsListViewModelTests.swift
- PIA VPN-tvOSTests/VPNConfigurationInstalling/Mocks/InstallVPNConfigurationUseCaseMock.swift
- PIA VPN.xcodeproj/project.pbxproj
- PIA VPN/SwiftGen+Strings.swift
- PIA VPN/en.lproj/Localizable.strings
- Search functionality on the Regions list
- Navigate from the Regions section to the regions search list when the search button is selected
> PIA-1001: Regions search

- PIA VPN/DashboardViewController.swift
It fixes an issue where the dynamic island was still visible in the latest know state after the user have logged out of the application.
> PIA-1108: Hide dynamic island on logout

- PIA VPN-tvOS/Navigation/AppRouter.swift
- PIA VPN-tvOS/Navigation/CompositionRoot/TopNavigationFactory.swift
- PIA VPN-tvOS/Navigation/Destinations.swift
- PIA VPN-tvOS/Navigation/Presentation/TopNavigationViewModel.swift
- PIA VPN-tvOS/Navigation/UI/TopNavigationView.swift
- PIA VPN-tvOS/PIA_VPN_tvOSApp.swift
- PIA VPN-tvOS/RegionsSelection/CompositionRoot/RegionsSelectionFactory.swift
- PIA VPN-tvOS/RegionsSelection/Presentation/RegionsContainerViewModel.swift
- PIA VPN-tvOS/RegionsSelection/Presentation/RegionsListViewModel.swift
- PIA VPN-tvOS/RegionsSelection/UI/RegionsContainerView.swift
- PIA VPN-tvOS/RegionsSelection/UI/RegionsListView.swift
- PIA VPN-tvOS/RootContainer/UserActivatedContainer/CompositionRoot/UserActivatedContainerFactory.swift
- PIA VPN-tvOS/RootContainer/UserActivatedContainer/UI/UserActivatedContainerView.swift
- PIA VPN-tvOS/Shared/UI/PIAColors+SwitUI.swift
- PIA VPN-tvOSTests/Dashboard/DashboardViewModelTests.swift
- PIA VPN-tvOSTests/Login/LoginIntegrationTests.swift
- PIA VPN-tvOSTests/Shared/AppRouterTests.swift
- PIA VPN-tvOSTests/Shared/TopNavigationViewModelTests.swift
- PIA VPN.xcodeproj/project.pbxproj
- PIA VPN/SwiftGen+Strings.swift
- PIA VPN/en.lproj/Localizable.strings
- Added support for navigating between the 4 main sections of the top bar: vpn, locations, settings and help
> PIA-1273: Add top navigation bar on the user authenticated flow

- .github/workflows/pull_request.yml
- fastlane/Fastfile
**Summary**
PIA-1265: tvOS unit tests ci setup
> PIA-1265: tvOS unit tests ci setup

- PIA VPN-tvOS/DedicatedIp/CompositionRoot/DedicatedIPFactory.swift
- PIA VPN-tvOS/DedicatedIp/Domain/Use cases/RemoveDIPUseCase.swift
- PIA VPN-tvOSTests/DedicatedIp/DedicatedIPViewModelTests.swift
- PIA VPN-tvOSTests/DedicatedIp/Mocks/ClientPreferencesMock.swift
- PIA VPN-tvOSTests/DedicatedIp/Mocks/DedicatedIPProviderMock.swift
- PIA VPN-tvOSTests/DedicatedIp/RemoveDIPUseCaseTests.swift
- PIA VPN.xcodeproj/project.pbxproj
**Summary**
This PR does the following when a DIP is deleted:
-  Removes DIP from favourite 
-  Disconnects VPN if DIP is selected server
> PIA-1388: Disconnect and remove favourite when deleting DIP

- PIA VPN-tvOS/Dashboard/CompositionRoot/DashboardFactory.swift
- PIA VPN-tvOS/Dashboard/UseCases/VpnConnectionUseCase.swift
- PIA VPN-tvOS/RegionsSelection/CompositionRoot/RegionsSelectionFactory.swift
- PIA VPN-tvOS/Shared/CompositionRoot/VpnConnectionFactory.swift
- PIA VPN-tvOS/Shared/StateMonitors/UserAuthenticationStatusMonitor.swift
- PIA VPN-tvOS/Shared/Utils/PIALibrary+Protocols/ClientPreferences+Protocols.swift
- PIA VPN-tvOSTests/Common/Mocks/ClientPreferencesMock.swift
- PIA VPN-tvOSTests/Common/VpnConnectionUseCaseTests.swift
- PIA VPN.xcodeproj/project.pbxproj
The problem this PR is solving:
- When connected to the Optimal Location and the app is killed, after opening back again the app, the location displayed as the connected one under the Optimal Location was always AU - Adelaide (the first location from the locations list), which was incorrect. The root cause was that once that the VPN connection succeeds we were not storing the current connected location as the `lastConnectedRegion` under the Client Preferences.
- Other glitch solved (in the 2nd commit of the PR):
- After signing out, the app still remained in the Account Settings screen. This was due to the Authentication State not being published under `handleAccountDidLogout` method
> PIA-1377: Cache the last connected location

- .github/workflows/pull_request.yml
- PIA VPN-tvOS.xctestplan
- PIA VPN-tvOS_E2E_Tests.xctestplan
- PIA VPN.xcodeproj/project.pbxproj
- PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA VPN-tvOS.xcscheme
- PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA-VPN_E2E_Tests.xcscheme
- PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA-VPN_tvOS_E2E_Tests.xcscheme
- PIA-VPN_E2E_Tests.xctestplan
- fastlane/Fastfile
- Remove tvOS e2e tests suite from the tvOS unit test test plan in order to keep the execution of these tests suites separate.
- Add a job in CI to run the tvOS e2e tests independently from the tvOS unit tests
> PIA-000: Separate tvOS e2e tests execution from tvOS Unit Tests

- PIA VPN-tvOS/RegionsSelection/Presentation/RegionsContainerViewModel.swift
- PIA VPN-tvOS/RegionsSelection/UI/RegionsContainerView.swift
- PIA VPN-tvOSTests/RegionsList/RegionsContainerViewModelTests.swift
- PIA VPN.xcodeproj/project.pbxproj
Improve the UX on the regions list navigation by:
- Set the focus of the region filter to the current selection when the focus returns back to the left side menu on regions list
> PIA-1389: Set the focus of the region filter to the current selection

- PIA VPN.xcodeproj/project.pbxproj
- This forces to always use the `fallback` value for all the strings on tvOS target. The fallback value is always in English
> PIA-1475: Default all the content of the tvOS app to show in English

- PIA VPN-tvOS/RegionsSelection/Presentation/RegionsContainerViewModel.swift
- PIA VPN-tvOSTests/RegionsList/Mocks/FavoriteRegionUseCaseMock.swift
- PIA VPN-tvOSTests/RegionsList/RegionsContainerViewModelTests.swift
This PR fixes the following bug:
- Bug where the regions list remains unusable and in an empty state when removing all the favorites items and the selected filter is Favorite.
Solution:
- When the selected filter is Favorites and all the favorite locations get removed from the list, then the selected section becomes the 'All' servers due to the Favorites section being removed from he left side menu.
> PIA-1476: Handle empty Favorites list when the selected filter is favorites

- .github/workflows/ios_pull_request.yml
- .github/workflows/tvos_pull_request.yml
Split pull request CI Workflow into 2, one per each platform (1 for tvOS and 1 for iOS):
- 1 workflow that builds the iOS app and runs the iOS Unit Test and the iOS e2eTests
- 1 workflow that builds the tvOS app and runs the tvOS Unit Test and the tvOS e2eTests
Note: there is also another [draft PR](https://github.com/pia-foss/mobile-ios/pull/110) that splits the workflows into 3 (instead of 2). But that PR consumes more time on CI because it has to build the iOS and the tvOS target twice. 
If we put all the tests for iOS on the same workflow and we run firs the Unit Tests, then running the e2e tests is actually 8minutes faster because it does not have to download the swift packages and compile the iOS target again since it uses the same derived data. And the same happens when we group …
> PIA-1443: Split CI workflows by platform

- PIA VPN-tvOS/Help/UI/AcknowledgementsView.swift
- PIA VPN-tvOS/RegionsSelection/UseCases/RegionsFilterUseCase.swift
- Filter out all the servers with a dip token from the regions 'all' servers (since the dip servers are displayed separately on the top section of the regions list next to the Optimal Location servers).
- Also fix a UI glitch that sometimes made not possible to scroll on the Acknowledgementes screen when moving the focus from any button on the top navigation bar to the Acknowledgments scroll view.
> PIA-1502: Fix duplicated dip on regions list when removing Dip server

- PIA VPN-tvOS/Dashboard/UI/DashboardView.swift
- PIA VPN-tvOS/Dashboard/UI/SelectedServerView.swift
- PIA VPN-tvOS/Help/UI/HelpOptionsView.swift
- PIA VPN-tvOS/RegionsSelection/UI/RegionsContainerView.swift
- PIA VPN-tvOS/Settings/UI/AvailableSettingsView.swift
- PIA VPN-tvOS/Shared/UI/PIAStyles.swift
- PIA VPN-tvOS/Shared/UseCases/RefreshServersLatencyUseCase.swift
- Set the focus to the first item of the Settings Screen when the screen appears (previously the focus was sometimes on the VPN button from the top navigation bar when the Settings and Options screens appear).
- Set the focus to the first item of the Options screen when the view appears.
- Fix a UI issue on the selected region section of the dashboard where the long names of servers appear truncated.
> PIA-1547: Handle default focus when Settings and Options appear

- PIA VPN.xcodeproj/project.pbxproj
- PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA VPN-tvOS.xcscheme
- PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA-VPN_E2E_Tests.xcscheme
- PIA VPN.xcodeproj/xcshareddata/xcschemes/PIA-VPN_tvOS_E2E_Tests.xcscheme
- PIA-VPN_E2E_Tests.xctestplan
- PIA-VPN_tvOS_E2E_Tests.xctestplan
- fastlane/Fastfile
**Summary**
added retry mechanism
> PIA-1574: optimise methods and tests

- PIA VPN-tvOS/Login/Utils/Foundation+PIA.swift
- PIA VPN-tvOS/Shared/Utils/Foundation+Protocols.swift
- PIA VPN-tvOS/Shared/Utils/PIALibrary+Protocols/PIALibrary+Protocols.swift
- PIA VPN-tvOS/Signup/CompositionRool/SignupFactory.swift
- PIA VPN-tvOSTests/Common/Mocks/AccountProviderTypeMock.swift
- PIA VPN-tvOSTests/Common/Mocks/NotificationCenterMock.swift
- PIA VPN.xcodeproj/project.pbxproj
- PIA VPN/AccountInformationAvailabilityFactory.swift
- PIA VPN/AccountInformationAvailabilityVerifier.swift
- PIA VPN/AccountObserver.swift
- PIA VPN/AppDelegate.swift
- PIA VPN/DashboardViewController.swift
- PIA VPN/UserDefaultsType.swift
- PIA VPNTests/AccountInformationAvailability/AccountInformationAvailabilityVerifierTests.swift
- PIA VPNTests/Mocks/UserDefaultsMock.swift
- This PR implements a new object called `AccountInformationAvailabilityVerifier` that checks whether the user information is available given a specific deadline. (For example, if the deadline is 12 hours, then the object does not check again if the last time it checked was less than 12 hours).
- This new object is called:
- When the app becomes active and the account information has not been checked in the last 12 hours.
- When the user taps the connect button and the account information has not been checked in the last 3 hours.
> PIA-922: Handle unauthorized user

- .github/workflows/development_build.yml
- .github/workflows/ios_pull_request.yml
- .github/workflows/ios_testflight_deploy.yml
- .github/workflows/tvos_pull_request.yml
- .github/workflows/tvos_testflight_deploy.yml
**Summary**
This PR sets XCode on CI to 15.2 due to a current issue we face with the simulator on XCode 15.3
> PIA-0000: Set XCode 15.2 on CI sue to simulator issue in 15.3

- PIA VPN-tvOS/LoginQR/Domain/Use cases/LoginWithReceiptUseCase.swift
**Summary**
This PR fixes a problem when recovering the purchase in Sign in, since it wasn't passing the real receipt to the API.
> PIA-1824: Recover purchases fix

- PIA VPN-tvOS/Signup/Presentation/SignupViewModel.swift
- PIA VPN-tvOS/Signup/Presentation/SubscriptionOptionViewModelMapper.swift
- PIA VPN-tvOS/Signup/UI/SignupView.swift
- PIA VPN-tvOS/SignupCredentials/UI/SignupCredentialsView.swift
- PIA VPN/SwiftGen+Strings.swift
- PIA VPN/en.lproj/Localizable.strings
**Summary**
This PR removes strings that are already translated in other keys so Translators don't have issues with the editor in Crowdin.
> PIA-1873: Remove duplicated strings

- PIA VPN-tvOS/Bootstraper/BootstraperFactory.swift
- PIA VPN-tvOS/DedicatedIp/Presentation/DedicatedIPViewModel.swift
- PIA VPN.xcodeproj/project.pbxproj
**Summary**
This PR fixes the DIP issue after migrating the Accounts screen by using the same `DefaultServerProvider` instance across the app. By using one single instance, we guarantee that we use the same Keychain instance as well which is required to save and fetch the dip token.
> KM-4856: Fix DIP on tvOS due to Accounts migrations

- PIA VPN.xcodeproj/project.pbxproj
**Summary**
This PR releases a hotfix for the network engine bug we had in version 3.25.0.
It sets the account Kotlin library as the default endpoint provider. The account implementation based on the new networking engine remains in the code but it's not used.
> Release hotfix v3.25.1

- PIA VPN/DashboardViewController.swift
- PIA VPN/PIAWelcomeViewController.swift
- When the Flag for force update gets enabled, the app might be in a state where any other view could be modally presented over the current context like settings, menu, options, etc. So we want to make sure that the Force Update screen is presented when intended also in those scenarios.
For more information, see the [CONTRIBUTING](/.github.com/CONTRIBUTING.md) readme or the contributing [guide](https://pia-oss.github.io/contribute).
**Summary**
> KM-5043: Dismiss any other view that is presented before showing Force Update

- .github/workflows/ios_pull_request.yml
- PIA VPN/AddCustomNetworksViewController.swift
- PIA VPN/TrustedNetworksViewController.swift
- fastlane/Fastfile
**Summary**
This PR fixes a couple of crashes that were happening when performing various actions on the "Manage Automation" settings screen. 
The root cause:
- Directly calling the collection view's data source methods to calculate the reference size of header and footer views, which deques views improperly. 
Fixes #
> KM-11906: Fix crashes on automation settings
